version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=learn-prisma
    ports:
      - '5443:5432'
    volumes:
      - ./db:/var/lib/postgresql/data